update spotify client
SarthakGupta22/personify pull request #3
Opened 2024-09-28 21:48 UTC by SarthakGupta22

Get song features from the track id

2024-09-28 22:22 UTC, ShrivatsAgrawal commented on src/api/spotify_client.py
> +        access_token: str | None = self.get_access_token()
Check is self.get_access_token already exists. If not exists then only create new one. Or if access token has expired. Will prevent many api calls.

2024-09-28 22:22 UTC, AbhinavAtrishi requested changes

2024-09-28 22:22 UTC, AbhinavAtrishi commented on src/api/spotify_client.py
> +spotify_client = SpotifyClient()
`if __name__ == "__main__"`

2024-09-28 22:24 UTC, ShrivatsAgrawal commented on src/api/spotify_client.py
> +        access_token: str | None = self.get_access_token()
Also assign to self.access_token for use by other functions

2024-09-29 00:23 UTC, ShrivatsAgrawal approved these changes

2024-09-29 00:23 UTC, sarthakkg approved these changes
Ship it

2024-09-29 00:23 UTC, merged